=== CSC-IT-Center-for-Science/orcidConnect/src/main/resources/xml_example.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="https://confluence.csc.fi/x/d4p5Aw" vc:minVersion="1.1"
  xmlns="https://confluence.csc.fi/x/d4p5Aw" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">
  <!-- TargetNamespace is to be defined with persistent URL -->
  <xs:element name="IdentitiesDescriptor">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded" minOccurs="1">
        <xs:element ref="IdentityDescriptor"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="IdentityDescriptor">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="1" ref="Identifier"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Identifier">
    <xs:complexType>
      <xs:all maxOccurs="1" minOccurs="1">
        <xs:element ref="Name" maxOccurs="1" minOccurs="1"/>
        <xs:element ref="NameFormat" maxOccurs="1" minOccurs="0"/>
        <xs:element ref="FriendlyName" maxOccurs="1" minOccurs="0"/>
        <xs:element ref="Issuer" maxOccurs="1" minOccurs="0"/>
        <xs:element ref="IssueInstant" maxOccurs="1" minOccurs="0"/>
        <xs:element ref="Mediator" maxOccurs="1" minOccurs="0"/>
        <xs:element ref="MediationInstant" maxOccurs="1" minOccurs="0"/>
        <xs:element ref="IdentifierValue" maxOccurs="1" minOccurs="1"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
  <xs:element name="Name" type="xs:string"/>
  <xs:element name="NameFormat" type="xs:anyURI"/>
  <xs:element name="FriendlyName" type="xs:string"/>
  <xs:element name="Issuer" type="xs:anyURI"/>
  <xs:element name="IssueInstant" type="xs:dateTime"/>
  <xs:element name="Mediator" type="xs:anyURI"/>
  <xs:element name="MediationInstant" type="xs:dateTime"/>
  <xs:element name="IdentifierValue" type="xs:anyType"/>
</xs:schema>

=== CSC-IT-Center-for-Science/orcidConnect/src/main/resources/xml_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<IdentitiesDescriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://confluence.csc.fi/x/d4p5Aw xml_example.xsd"
 xmlns="https://confluence.csc.fi/x/d4p5Aw">
    <IdentityDescriptor>
        <Identifier><Name>urn:oid:1.3.6.1.4.1.5923.1.1.1.16</Name>
            <NameFormat>
            urn:oasis:names:tc:SAML:2.0:attrname-format:uri</NameFormat>
            <FriendlyName>eduPersonOrcid</FriendlyName>
            <Issuer>http://api.sandbox.orcid.org/</Issuer>
            <IssueInstant>2015-04-23T13:32:43Z</IssueInstant>
            <Mediator>https://orcid-connect01.csc.fi/</Mediator>
            <MediationInstant>2016-02-23T08:23:05Z</MediationInstant>
            <IdentifierValue> http://sandbox.orcid.org/0000-0003-0833-4032</IdentifierValue>
        </Identifier>
        <Identifier>
            <Name>urn:oid:1.3.6.1.4.1.5923.1.1.1.6</Name>
            <NameFormat>urn:oasis:names:tc:SAML:2.0:attrname-format:uri</NameFormat>
            <FriendlyName>eduPersonPrincipalName</FriendlyName>
            <Issuer>https://testidp.funet.fi/idp/shibboleth</Issuer>
            <!--<IssueInstant></IssueInstant>-->
            <Mediator>https://orcid-connect01.csc.fi/</Mediator>
            <MediationInstant>2016-02-23T08:23:05Z</MediationInstant>
            <IdentifierValue>teppo@yliopisto.fi</IdentifierValue>
        </Identifier>
    </IdentityDescriptor>
</IdentitiesDescriptor>
